feat(parser): Added Telegram parser and flow to processing data
ffmemes/ff-backend pull request #1
Opened 2023-12-25 10:46 UTC by ohld

2023-12-25 11:02 UTC, ohld commented on src/storage/parsers/snscrape/version.py
> +try:
удали у себя локально пакет snscrape и попробуй запустить заново и удалить все ненужные неиспользуемые функции.

2023-12-25 11:02 UTC, ohld commented on src/storage/parsers/telegram.py
> +if __name__ == '__main__':
убери из всех своих файлов 
if __name__ == '__main__':

2023-12-25 11:02 UTC, ohld commented on src/storage/parsers/telegram.py
> +import pandas as pd
мы можем не использовать библиотеку pandas?

2023-12-25 11:02 UTC, ohld commented on src/utils.py
> +def generate_flow_run_name():
1. а что, он сам не генерит названия флоу? 
2. Если эта функция действительно нужна, то почему она не в src/flows/utils.py ?

2023-12-25 11:11 UTC, SUPERustam commented on Dockerfile.flow
> +CMD ["python", "flow_deployments/parsers.py", "serve_flow"]
На 5 строчке можно добавить --no-cache-dir к `pip install -U pip`

2023-12-25 11:12 UTC, ohld commented on Dockerfile.flow
> +CMD ["python", "flow_deployments/parsers.py", "serve_flow"]
Это не ответ)

2023-12-25 11:15 UTC, aleksspevak commented on Dockerfile.flow
> +CMD ["python", "flow_deployments/parsers.py", "serve_flow"]
Это докерфайл для воркера, делал по [документации](https://docs.prefect.io/latest/guides/docker/).
Он собирает все флоу в контейнер и ждет вызова через UI или вызова flow.

2023-12-25 11:16 UTC, aleksspevak commented on docker-compose.yml
> +      - app_db
Это воркер для флоу, насколько я понял он должен содержать flows для их запуска.

2023-12-25 11:46 UTC, aleksspevak commented on flow_deployments/parsers.py
> +    for deployment_name, deployment_flow in deployments.items():
Нам вообще нужна функция deploy()?
Все flow попадают в воркел и Perfect через serve_flow()

2023-12-25 11:51 UTC, aleksspevak commented on flow_deployments/parsers.py
> +    globals()[sys.argv[1]]()
Как потом взаимодействовать с этим деплоем?
Протсо я пока в доке не нашел как взаимодействовать с такими деплоями потом, где будет запускаться flow?
if name уберу, он просто для облегчения запуска функций из вне был

2023-12-25 13:10 UTC, ohld commented on docker-compose.yml
> +      - app_db
Думаю, как минимум стоит Dockerfile.flow переменовать в Dockerfile.prefect, а-то непонятно.

2023-12-25 13:12 UTC, ohld commented on flow_deployments/parsers.py
> +    globals()[sys.argv[1]]()
Я понимаю так:
1. Есть prefect cloud, который scheduler и триггерит нужные таски 
2. Есть prefect worker, который мы запускаем у себя на сервере, который слушает prefect cloud и выполняет задачу
3. есть flow_deployments - скрипты, которые регистрируют в prefect cloud новые функции / меняют расписания у созданных. Запускаем только тогда, когда изменилось schedule или просто для регистрации новой таски  в prefect cloud
4. есть src/flows - это реализация конкретных @flow и @task

2023-12-25 15:15 UTC, aleksspevak commented on src/utils.py
> +def generate_flow_run_name():
Мне не нравятся имена, они не слишком инфрмативны. Удалил.

2023-12-25 21:20 UTC, VeryBigSad requested changes
В целом все отлично, но хочется пару небольших фиксов

2023-12-25 21:20 UTC, VeryBigSad commented on src/database.py
> +    Column("post_id", String, nullable=False),
разве это не должно быть `int`? Для идшников постов в тг

2023-12-25 21:20 UTC, VeryBigSad commented on requirements/base.txt
> +psycopg2==2.9.*
Разве мы не можем юзать `asyncpg`? Он может быть в [несколько раз быстрее](https://github.com/MagicStack/asyncpg)

2023-12-25 21:31 UTC, VeryBigSad approved these changes

2023-12-26 11:15 UTC, ohld commented on src/database.py
> +    Column("out_links", ARRAY(String)),
Я же просил JSON юзать

2023-12-26 11:15 UTC, ohld commented on flow_deployments/parsers.py
> +def deploy():
зачем ты это оборачиваешь в функцию? Я же написал пример в этом же файле выше, как оформлять эти функции.

2023-12-26 11:15 UTC, ohld commented on flow_deployments/parsers.py
> +def serve_flow():
здесь аналогично, зачем тут функция?

2023-12-26 11:15 UTC, ohld commented on src/flows/parsers/telegram.py
> +@flow(name="Parse raw telegram",
codestyle:
``` python
@flow(
    name="Parse raw telegram",
    ....
)
def parse_telegram_source() -> None:
    ....
```

2023-12-26 11:15 UTC, ohld commented on src/storage/parsers/telegram.py
> +        post["post_id"] = post["url"].split("/")[-1]
проверка, что `isinstance(post_id, int)`?

2023-12-26 12:24 UTC, aleksspevak commented on src/database.py
> +    Column("out_links", ARRAY(String)),
Там приходит обычным массивом данные, где использовал array string
json вида {"data":[]} хранить?

2023-12-26 12:32 UTC, aleksspevak commented on src/storage/parsers/telegram.py
> +        post["post_id"] = post["url"].split("/")[-1]
А если не int, то вызывать ошибку?

2023-12-26 12:38 UTC, ohld commented on src/database.py
> +    Column("out_links", ARRAY(String)),
Исправь просто тип столбца на JSONB

```
from sqlalchemy.dialects.postgresql import JSONB
```

добавлять вокруг списка {data: []} не надо

2023-12-26 12:40 UTC, ohld commented on requirements/base.txt
> +psycopg2==2.9.*
вроде как все ок с этим

2023-12-26 12:53 UTC, merged