added automatic text size selection
ffmemes/ff-backend pull request #15
Opened 2024-01-30 21:33 UTC by Antohhin

- добавил папку с одним из [популярных](https://github.com/larsenwork/Gidole) шрифтов `/src/fonts/Gidole-Regular.ttf`
- новая функция подборки размера текста относительно размера картинки check_font_size()
за этим стоит следующая идея:
1. задать width_ratio какой пропорции относительно размера картинки текст должен быть
2. задать начальные значения fontsize, learning_rate, где последнее это шаг с которым будем регулировать размер текста
3. уменьшать/увеличивать текст пока не выбью breakpoint (идея как в бинарном поиске, чтоб поживее, но не перескочить)
4. подгружаю шрифт с выбранным размером `ImageFont.truetype(font_path, fontsize)`

 
![картинка в высоком разрешении](https://github.com/ffmemes/ff-backend/assets/71396012/f80c791f-9c59-40ed-b697-c68564651640)
![картинка для сравнения (справа старая вотермарка)](https://github.com/ffmemes/ff-backend/assets/71396012/1b7da01a-f30c-4a58-861c-6aa2f668df3e)
![шакальная картинка, честно говоря, так себе работает](https://github.com/ffmemes/ff-backend/assets/71396012/60b82702-964d-436b-977d-ec9ea56e47a0)

2024-01-30 21:48 UTC, ohld commented
Все статические файлы (не относящиеся к питоновскому коду) должны находиться в папке static.

2024-01-30 21:49 UTC, ohld commented on src/storage/watermark.py
> +    buff.name = 'image_x.jpeg'
почему поменял?)

2024-01-30 21:49 UTC, ohld requested changes

2024-01-30 21:49 UTC, ohld commented on src/storage/watermark.py
> +# if __name__ == '__main__':
закомментрированное нужно убрать

2024-01-30 21:54 UTC, Antohhin commented
> Все статические файлы (не относящиеся к питоновскому коду) должны находиться в папке static.

папку fonts там создать или просто шрифт положить?

2024-01-30 21:54 UTC, Antohhin commented on src/storage/watermark.py
> +    buff.name = 'image_x.jpeg'
тестил, забыл убрать

2024-01-30 22:04 UTC, ohld commented
Папку fonts, да.

2024-01-30 22:06 UTC, ohld commented on src/storage/watermark.py
> +        font_path = str(Path(Path.home(), "src", "fonts", font_family))
Не уверен, что этот способ работы с путями сработает. Посмотри, как я с путями работаю в localizer, когда считываю yml файлы из папки static.

2024-01-30 22:07 UTC, ohld commented on src/storage/watermark.py
> +            learning_rate = learning_rate // 2
Если честно я не понимаю, зачем тут бесконечный цикл и такой сложный алгоритм. Разве нельзя по размеру картинки прикинуть размер шрифта?

2024-01-31 13:35 UTC, Antohhin commented on src/storage/watermark.py
> +            learning_rate = learning_rate // 2
1. шрифт — величина относительная (12, 18, 75 не понятно нифига это много или мало для картинки).
поэтому, в моем видении, этот алгоритм занимается как раз прикидкой размера шрифта под размер картинки.
2. по поводу `while True` — могу предложить другой вариант:
сделать маленькое значение font и идти только на увеличение текста `while font.getlength(text) < breakpoint`
будет работать быстрее

2024-01-31 13:40 UTC, Antohhin commented on src/storage/watermark.py
> +        font_path = str(Path(Path.home(), "src", "fonts", font_family))
ага, понял
вообще я через докер поднимал, как в описании, тестил через Ipython и работало.
правильно понял, ты предлагаешь переписать через контекстный менеджер?
```python
with open(localization_file, "r") as f:
            localizations |= yaml.safe_load(f)
```

2024-02-11 10:18 UTC, ohld commented
<img width="183" alt="image" src="https://github.com/ffmemes/ff-backend/assets/5613295/7ac7d079-c12c-4ccf-8053-ffc77d59f17c">

???

2024-02-11 10:24 UTC, Antohhin commented
> <img alt="image" width="183" src="https://private-user-images.githubusercontent.com/5613295/303911700-7ac7d079-c12c-4ccf-8053-ffc77d59f17c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2NDcyNDUsIm5iZiI6MTcwNzY0Njk0NSwicGF0aCI6Ii81NjEzMjk1LzMwMzkxMTcwMC03YWM3ZDA3OS1jMTJjLTRjY2YtODA1My1mZmM3N2Q1OWYxN2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTFUMTAyMjI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmJkMjZhYTUyMGU4MmQ2ODI2NzNkYjJjMWEzNjU4ZTQ0YjkzYTk4MGExYzBjNzRlZmJlNzIxYTcxMDA5NzU3MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.A-NpuPies8QVT87X4yP93Tu0_ynElS-rbseuqhykMms">
> ???

win+wsl 😭 
откачу, либо просто другой ПР создам

2024-02-11 10:27 UTC, closed without merging

2024-02-11 10:28 UTC, Antohhin commented
сделаю клон этого PR