Deduplication ocr text
ffmemes/ff-backend pull request #23
Opened 2024-02-07 15:00 UTC by SUPERustam

1. add to Postgres built-in extension `CREATE EXTENSION pg_trgm;`
2. Can't test python code without db tokens. Tested SQL code in [metabase](https://metabase.okhlopkov.com/question/100-deduplication)
3. Table of results with [duplications](https://github.com/SUPERustam/ocr_example/blob/master/images/dupblication.csv). 5/12 accuracy
4. Use coefficient 0.9 not 1 because 0.9 indicate that 2 strings are very similar

Playground: https://metabase.okhlopkov.com/question/116-my1

2024-02-07 17:35 UTC, ohld requested changes

2024-02-07 17:35 UTC, ohld commented on src/storage/service.py
> +        res = min(meme_id, res["id"])
Так как эта функция стачала будет вызываться для старых мемов, а потом для новых (когда они парсятся), достаточно в SQL написать  `WHERE M.id <= :meme_id`. Также стоит добавить фильтр, чтобы алгоритм не выдавал мемы, которые уже помечены как дубликаты. Чтобы не было "цепочек" (этот дубль от этого, а сам этот - от другого), а все одинаковые мемы "сливались" в один, который был добавлен раньше всего в базу.

2024-02-07 17:35 UTC, ohld commented on src/storage/service.py
> +    if len(imagetext) < 3:  # skip all memes with less than 3 letters
почему именно <3? (то есть 0, 1 и 2 буквы в тексте на меме). Сколько всего таких мемов? Почему не 10?

2024-02-09 10:11 UTC, SUPERustam commented on src/storage/service.py
> +        res = min(meme_id, res["id"])
Предлагаю делать  `WHERE M.id < :meme_id`чтобы сам с собой не сравнивал

2024-02-09 10:39 UTC, SUPERustam commented on src/storage/service.py
> +    if len(imagetext) < 3:  # skip all memes with less than 3 letters
Изменю на 11, так до 11 в основном @ffmemesbot тексты: https://metabase.okhlopkov.com/question/118-length-of-ocr-texts

2024-02-09 10:39 UTC, SUPERustam commented on src/storage/service.py
> +        res = min(meme_id, res["id"])
Обновил запрос: https://metabase.okhlopkov.com/question/100-deduplication

2024-02-10 10:25 UTC, merged