New VK parser
ffmemes/ff-backend pull request #7
Opened 2023-12-30 22:53 UTC by aleksspevak

2023-12-31 08:26 UTC, aleksspevak commented
@ohld Подскажи как ты тестил тг парсер и закидывал в клауд? Хочу в своем протестить.
Если запускать `python flow_deployments/parsers.py`, то не работает, так переменные у нас через FastAPI инициализируются. 
В самом приложение не нашел функций для запуска деплоя.

2023-12-31 15:09 UTC, VeryBigSad requested changes
Все отлично, главное протестить, что это работает)
Хотел бы переименовать .env значение + `date` в более явный `posted_at`

2023-12-31 15:09 UTC, VeryBigSad commented on src/config.py
> +    VK_TOKEN: str | None = None
bot или user токен?

2023-12-31 15:09 UTC, VeryBigSad commented on src/database.py
> +    Column("date", DateTime, nullable=False),
переименовать бы в `posted_at`

2023-12-31 15:09 UTC, VeryBigSad commented on src/storage/parsers/vk.py
> +        self.vk_source_link = "https://vk.com/%s" % vk_source
`%s` выглядит грустно
понимаю, что это скопированный кусок, но в будущем не хотелось бы такого страшного кода, как эта функция, в проекте

2023-12-31 15:45 UTC, ohld commented
@aleksspevak чекни ридми. Ты можешь запустить весь бекенд через docker compose up, а потом через docker compose exec python (см ридми) запустить питон в окружении бекенда, импортировать твою функцию и проверить ее

2023-12-31 15:46 UTC, ohld commented on src/database.py
> +    Column("date", DateTime, nullable=False),
у нас уже в meme_raw_tg уже date, потому что это поле, которое выдает парсер тг. Не знаю, как лучше

2023-12-31 16:33 UTC, VeryBigSad commented on src/database.py
> +    Column("date", DateTime, nullable=False),
тогда норм
в целом таблица отражает данные, которые мы получаем с вк, так что окей

2024-01-02 13:32 UTC, ohld approved these changes

2024-01-02 13:33 UTC, ohld approved these changes

2024-01-02 13:34 UTC, merged